class ChatModel {
  String name;
  String icon;
  bool isGroup;
  String time;
  String currentMessage;
  ChatModel(this.name, this.icon, this.isGroup, this.time, this.currentMessage);
}

List<ChatModel> users = [
  ChatModel('John', "https://source.unsplash.com/random/100x100/?happyfaces", false, '10:30 AM', 'Hello, how are you?'),
  ChatModel('Alice', "https://source.unsplash.com/random/100x100/?angryfaces", false, '11:45 AM', 'I had a tough day.'),
  ChatModel('Bob', "https://source.unsplash.com/random/100x100/?faces", false, '09:15 AM', 'Good morning!'),
  ChatModel('Sarah', "https://source.unsplash.com/random/100x100/?funnyfaces", false, '02:00 PM', 'Did you hear the news?'),
  ChatModel('David', "https://source.unsplash.com/random/100x100/?surprisedfaces", false, '03:30 PM', 'Surprise!'),
  ChatModel('Emily', "https://source.unsplash.com/random/100x100/?happydogs", false, '08:00 AM', 'Woof woof!'),
  ChatModel('Grace', "https://source.unsplash.com/random/100x100/?beautiful-landscapes", false, '05:30 PM', 'Nature is beautiful.'),
  ChatModel('Ethan', "https://source.unsplash.com/random/100x100/?colorful-flowers", false, '12:30 PM', 'Flowers everywhere!'),
  ChatModel('Olivia', "https://source.unsplash.com/random/100x100", false, '04:45 PM', 'Just checking in.'),
  ChatModel('Michael', "https://source.unsplash.com/random/100x100/?happyfaces", false, '09:00 AM', 'Good morning, everyone!'),
  ChatModel('Sophia', "https://source.unsplash.com/random/100x100/?angryfaces", false, '03:15 PM', 'I need a break.'),
  ChatModel('Liam', "https://source.unsplash.com/random/100x100/?faces", false, '02:30 PM', 'What\'s the plan for today?'),
  ChatModel('Ava', "https://source.unsplash.com/random/100x100/?funnyfaces", false, '10:45 AM', 'Haha, that\'s hilarious!'),
  ChatModel('Noah', "https://source.unsplash.com/random/100x100/?surprisedfaces", false, '04:00 PM', 'I can\'t believe it!'),
  ChatModel('Mia', "https://source.unsplash.com/random/100x100/?happydogs", false, '11:30 AM', 'Anyone up for a dog walk?'),
  ChatModel('James', "https://source.unsplash.com/random/100x100/?beautiful-landscapes", false, '01:45 PM', 'Nature is my escape.'),
  ChatModel('Emma', "https://source.unsplash.com/random/100x100/?colorful-flowers", false, '12:15 PM', 'Flowers make me smile.'),
  ChatModel('William', "https://source.unsplash.com/random/100x100", false, '08:45 AM', 'How\'s everyone doing today?'),
  ChatModel('Lily', "https://source.unsplash.com/random/100x100/?smilingfaces", false, '02:30 PM', 'Hi there!'),
  ChatModel('Lucas', "https://source.unsplash.com/random/100x100/?sadfaces", false, '01:15 PM', 'Feeling down today.'),
  ChatModel('Sophie', "https://source.unsplash.com/random/100x100/?friendlyfaces", false, '10:00 AM', 'Good morning, sunshine!'),
  ChatModel('Jackson', "https://source.unsplash.com/random/100x100/?confusedfaces", false, '03:45 PM', 'I\'m so confused.'),
  ChatModel('Aiden', "https://source.unsplash.com/random/100x100/?laughingfaces", false, '11:00 AM', 'Hahaha!'),
  ChatModel('Scarlett', "https://source.unsplash.com/random/100x100/?beautifulfaces", false, '05:15 PM', 'Beauty in everything.'),
  ChatModel('Henry', "https://source.unsplash.com/random/100x100/?sleepyfaces", false, '09:30 AM', 'I need more sleep.'),
  ChatModel('Zoe', "https://source.unsplash.com/random/100x100/?cuteanimals", false, '12:45 PM', 'Cuteness overload!'),
  ChatModel('Jackson', "https://source.unsplash.com/random/100x100/?excitedfaces", false, '08:30 AM', 'Exciting news!'),
  ChatModel('Ella', "https://source.unsplash.com/random/100x100/?happyfaces", false, '03:00 PM', 'Happy vibes only.'),
  ChatModel('Matthew', "https://source.unsplash.com/random/100x100/?surprisedfaces", false, '10:15 AM', 'You won\'t believe this!'),
  ChatModel('Grace', "https://source.unsplash.com/random/100x100/?angryfaces", false, '02:45 PM', 'I\'m really angry right now.'),
  ChatModel('Liam', "https://source.unsplash.com/random/100x100/?funnyfaces", false, '11:30 AM', 'Laughter is the best medicine.'),
  ChatModel('Olivia', "https://source.unsplash.com/random/100x100/?happydogs", false, '04:15 PM', 'Doggos make me smile.'),
  ChatModel('Ethan', "https://source.unsplash.com/random/100x100/?beautiful-landscapes", false, '12:00 PM', 'Nature walks are my therapy.'),
  ChatModel('Chloe', "https://source.unsplash.com/random/100x100/?colorful-flowers", false, '08:45 AM', 'Flowers brighten my day.'),
  ChatModel('Daniel', "https://source.unsplash.com/random/100x100", false, '01:30 PM', 'What\'s up, folks?'),
  ChatModel('Aria', "https://source.unsplash.com/random/100x100/?cuteanimals", false, '09:45 AM', 'Adorable creatures!'),
  ChatModel('William', "https://source.unsplash.com/random/100x100/?friendlyfaces", false, '02:15 PM', 'Friendly faces everywhere!'),
  ChatModel('Mia', "https://source.unsplash.com/random/100x100/?smilingfaces", false, '10:45 AM', 'Smile more, worry less.'),
  ChatModel('James', "https://source.unsplash.com/random/100x100/?sadfaces", false, '03:15 PM', 'Tough times, stay strong!'),
  ChatModel('Emily', "https://source.unsplash.com/random/100x100/?excitedfaces", false, '12:30 PM', 'Exciting plans ahead!'),
  ChatModel('Sophia', "https://source.unsplash.com/random/100x100/?beautifulfaces", false, '11:00 AM', 'Beauty is all around us.'),
  ChatModel('Noah', "https://source.unsplash.com/random/100x100/?confusedfaces", false, '04:45 PM', 'Confused but hopeful.'),
  ChatModel('Charlotte', "https://source.unsplash.com/random/100x100/?laughingfaces", false, '08:00 AM', 'Laughter is contagious!'),
  ChatModel('Benjamin', "https://source.unsplash.com/random/100x100/?sleepyfaces", false, '01:00 PM', 'I need a nap.'),
  ChatModel('Ava', "https://source.unsplash.com/random/100x100/?angryfaces", false, '05:30 PM', 'Angry bird here!'),
  ChatModel('Logan', "https://source.unsplash.com/random/100x100/?funnyfaces", false, '09:00 AM', 'Life is a joke sometimes.'),
  ChatModel('Amelia', "https://source.unsplash.com/random/100x100/?happydogs", false, '02:00 PM', 'Dogs make everything better.'),
  ChatModel('Jacob', "https://source.unsplash.com/random/100x100/?beautiful-landscapes", false, '11:15 AM', 'Nature lover.'),
  ChatModel('Harper', "https://source.unsplash.com/random/100x100/?colorful-flowers", false, '03:30 PM', 'Flowers bring joy.'),
  ChatModel('Elijah', "https://source.unsplash.com/random/100x100/?friendlyfaces", false, '12:15 PM', 'Friendship is precious.'),
  ChatModel('Evelyn', "https://source.unsplash.com/random/100x100/?smilingfaces", false, '09:15 AM', 'Keep smiling!'),
  ChatModel('Liam', "https://source.unsplash.com/random/100x100/?surprisedfaces", false, '02:15 PM', 'Life is full of surprises.'),
  ChatModel('Ella', "https://source.unsplash.com/random/100x100/?cuteanimals", false, '10:30 AM', 'Cuteness overload!'),
  ChatModel('Mason', "https://source.unsplash.com/random/100x100/?excitedfaces", false, '04:00 PM', 'Exciting times ahead!'),
  ChatModel('Avery', "https://source.unsplash.com/random/100x100/?beautifulfaces", false, '08:45 AM', 'Beauty in simplicity.'),
  ChatModel('Jackson', "https://source.unsplash.com/random/100x100/?laughingfaces", false, '01:45 PM', 'Laughter is timeless.'),
  ChatModel('Scarlett', "https://source.unsplash.com/random/100x100/?angryfaces", false, '05:00 PM', 'Anger management needed!'),
  ChatModel('Benjamin', "https://source.unsplash.com/random/100x100/?sleepyfaces", false, '11:30 AM', 'Dreaming of a nap.'),
];
